imagePullSecrets: []

camera:
  image: localhost:5001/thavlik/homesec-camera:latest
  imagePullPolicy: Always
  logLevel: info
  resources:
    requests:
      memory: "512Mi"
      cpu: "1000m"
    limits:
      memory: "512Mi"
      cpu: "2000m"

mixer:
  image: localhost:5001/thavlik/homesec-mixer:latest
  imagePullPolicy: Always
  logLevel: info
  replicas: 1
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"

gui:
  image: localhost:5001/thavlik/homesec-gui:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
