imagePullSecrets: []

picamera:
  image: 192.168.0.101:5000/thavlik/homesec-picamera:latest
  imagePullPolicy: Always
  logLevel: info
  resources:
    requests:
      memory: "512Mi"
      cpu: "1000m"
    limits:
      memory: "512Mi"
      cpu: "2000m"

mixer:
  image: thavlik/homesec-mixer:latest
  imagePullPolicy: Always
  logLevel: info
  replicas: 1
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"

gui:
  image: thavlik/homesec-gui:latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
