[workspace]
default-members = [
  "bootstrap",
  "drivers/camera/core",
  #"drivers/camera/picamera",
  "drivers/temperature/ds18b20",
  "mixer",
  "test",
]
members = [
  "bootstrap",
  "drivers/camera/core",
  #"drivers/camera/picamera",
  "drivers/temperature/ds18b20",
  "mixer",
  "test",
]

