apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-picamera
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-picamera
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-picamera
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: {{ .Release.Name }}-privileged
      containers:
      - name: picamera
        image: thavlik/homesec-picamera:latest
        command:
        - python
        - main.py
        - --mixer-uri
        - http://{{ .Release.Name }}-mixer:4321
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            memory: 256Mi
        securityContext:
          privileged: true
      nodeSelector:
        picamera: yes
