apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-picamera
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-privileged
      containers:
      - name: picamera
        image: thavlik/homesec-picamera:latest
        command:
        - python
        - main.py
        - --mixer-uri
        - {{ .Release.Name }}-mixer.{{ .Release.Namespace }}.svc.cluster.local:4321
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 1000m
            memory: 512Mi
        securityContext:
          privileged: true
      nodeSelector:
        camera: "yes"
