apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mixer
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - name: service
    port: 4321
    targetPort: 4321
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-mixer

